// Generated by Wrangler on Sat Apr 20 2024 21:23:47 GMT+0100 (Western European Summer Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	kv: KVNamespace;
	db: D1Database;
}
