#:schema node_modules/wrangler/config-schema.json
name = "polls"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[kv_namespaces]]
binding = "kv"
id = "52bde25a41294882b70568010e895a18"

[[d1_databases]]
binding = "db"
database_name = "polls"
database_id = "6c75b44b-f9f2-4737-b915-a532436b8bc7"
migrations_dir = "prisma/d1"
